version: "3.9"

services:
  passbolt:
    container_name: passbolt
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    image: passbolt/passbolt:latest
    environment:
      APP_FULL_BASE_URL: https://passbolt.local
      DATASOURCES_DEFAULT_DRIVER: Cake\Database\Driver\Postgres
      DATASOURCES_DEFAULT_ENCODING: "utf8"
      DATASOURCES_DEFAULT_URL: "postgres://passbolt:P4ssb0lt@db:5432/passbolt?schema=passbolt"
      EMAIL_TRANSPORT_DEFAULT_HOST: "smtp.domain.tld"
      EMAIL_TRANSPORT_DEFAULT_PORT: 587
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
      # - ./cert.pem:/etc/ssl/certs/certificate.crt:ro
      # - ./key.pem:/etc/ssl/certs/certificate.key:ro
      # - ./cert.pem:/etc/passbolt/certs/certificate.crt:ro
      # - ./key.pem:/etc/passbolt/certs/certificate.key:ro
    ports:
      - 80:80
      - 443:443
      #Alternatively for non-root images:
      # - 80:8080
      # - 443:4433
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    command: >
      bash -c "/usr/bin/wait-for.sh -t 0 db:5432 -- /docker-entrypoint.sh"

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "passbolt"
      POSTGRES_USER: "passbolt"
      POSTGRES_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
